#!/bin/bash
(
  cd buildroot-2020.02
  output/host/bin/qemu-system-arm  -M vexpress-a9 -nographic -smp 1 -m 256 -kernel output/images/zImage -dtb output/images/vexpress-v2p-ca9.dtb -append "console=ttyAMA0,115200" -net nic,model=lan9118 -net user
)
